name: 'ServiceNow CI/CD Install App - Custom Domain Enabled'
description: 'Installs the specified application from the application repository onto the specified instance.'
author: "ServiceNow"
inputs:
  version:
    description: "Application version to install"
    required: true
  baseAppVersion:
    description: "Version of the base application on which to apply the customizations"
    required: false
  autoUpgradeBaseApp:
    description: "Only applicable if Application Customization is active and the associated application is a higher version than the currently installed version"
    required: false
outputs:
  rollbackVersion:
    description: "Previously installed app's version, used to roll-back task"
runs:
  using: 'node12'
  main: './lib/index.js'
branding:
  icon: 'refresh-ccw'
  color: 'green'
